@startuml
autonumber

mainframe **Command: Data collection**

actor "Client(**Jenkins**)" as C
boundary Interface as I
entity Collector as CE

box Independent #LightBlue
entity "CollectorEngine(Y, J, L)" as M
end box

control DBHandler as DBH
database Database as DB

C -> I ++: Collect data
    loop #transparent until stop signal from Client
        I -> CE ++: Run
            CE -> M ++: Collect data
                M -> M ++: Collect data
                deactivate

                M -> DBH ++: Request insertion
                    DBH -> DB ++: Insert data
                    return Result
                return Result
            return Result
        return Result
    end

    return Collection result
@enduml
